export const langs = {
  ru: {
    code: 'ru',
    codeName: 'Ру',
    name: 'Русский',
    name_game: 'Battle of tanks',
    workShopTitle: 'Мастерская',
    options: {
      health: 'HP',
      speed: 'Скорость передвижения',
      speedRotate: 'Маневренность',
      speedRotateTower: 'Скорость вращения башни',
      accuracy: 'Точность наведения',
      timeRefreshWeapon: 'Время перезарядки',
      distanceView: 'Дистанция наведения',
      speedShot: 'Скорость снарядов',
      distanceShot: 'Дистанция стрельбы'
    },
    weapons: {
      default: 'Обычный',
      fire: 'Зажигательный',
      armour: 'Бронебойный',
      energy: 'Энергетический',
      fosfor: 'Фосфорный'
    },
    weapon: 'снаряд',
    activeWeapon: 'Активный снаряд - %s',
    noneWeapon: 'Закончился %s снаряд!',
    norank: 'Требуется звание - \r\n',
    rank: [
      'Ефрейтор',
      'Мл. сержант',
      'Сержант',
      'Лейтенант',
      'Ст. лейтенант',
      'Капитан',
      'Майор',
      'Подполковник',
      'Полковник'
    ],
    update: 'Улучшить',
    updateTitle: 'Улучшение ТТХ',
    updateText: 'Вы хотите улучшить %s на %s% за %s монет?',
    updateTextSlider:
      'Перетаскивайте слайдер(белый круг), чтобы выбрать необходимый уровень улучшения',
    shopTitle: 'Магазин',
    stretch: 'Сила',
    check: 'Выбрать',
    cart: 'Купить',
    cartTitle: 'Покупка',
    cartText: 'Вы хотите купить %s за %s монет?',
    inGaraz: 'В гараже',
    tanks: 'Техника',
    artefact: 'Артефакты',
    repair: 'Восстановление',
    maxValue: 'Максимум',
    notMany: 'Не хватает монет',
    bank: 'Банк',
    bankDescription: 'Здесь можно получить монеты за портальную валюту или просмотр рекламы',
    bankGetMoneyByAdv: 'Получить 100 монет за просмотр рекламы',
    return: 'Назад',
    getAdv: 'Получить за просмотр рекламы',
    getYan: 'Получить за %s янов',
    getCoinSuccess: '%s монет успешно добавлены на ваш счет!',
    backToBank: 'Заходите за монетами в любое время!',
    controlTitle: 'Настройки',
    exitFromRound: 'Завершить раунд',
    gameOverPlayer: 'Вы проиграли, но не отчаивайтесь, вы всегда можете начать новый раунд!',
    winTeam: 'Ваша команда одержала победу',
    roundReward: 'В этом раунде вы заработали %s монет!',
    gameOverTitle: 'Поражение',
    winTitle: 'Победа',
    getReward: 'Забрать награду',
    getReward2: 'Забрать удвоенную награду, просмотрев рекламу',

    record: 'Ваш рекорд',
    level: 'Раунд',
    level_completed: 'Раунд завершен',
    pause: 'Пауза',
    create_bomb_help: 'У вас нет доступных молний! Хотите создать молнию за просмотр рекламы?',
    ok: 'Да',
    cancel: 'Нет',
    gameover_title: 'Игра проиграна',
    gameover_btn_continue_by_adv: 'Продолжить за просмотр рекламы',
    gameover_btn_new_game: 'Начать новую игру',
    current_score: 'Текущий счет',
    btnToBattle: 'В бой',
    btn_continue: 'Продолжить игру',
    leaderboard_title: 'Лидеры в игре',
    lang_title: 'Язык в игре',
    close: 'Закрыть',
    add_bomb_max: 'За уничтожение самых больших шаров, вы получаете бонус - огненную молнию!',
    add_bomb_seria: 'За большую серию уничтожений шаров, вы получаете бонус - огненную молнию!',
    next: 'Далее',
    bonusText: [
      '',
      '',
      'Отлично',
      'Прекрасно',
      'Здорово',
      'Блестяще',
      'Так держать',
      'Круто',
      'Искусно',
      'Браво',
      'Фантастика',
      'Чудесно',
      'Ты талант',
      'Ты звезда'
    ],
    job: 'Задание: Уничтожить следующие шары',
    help: {
      help_move: {
        title: 'Прицелься и брось шарик',
        text: 'Перемещай каретку - перемещая мышь над полем с шариками (нажми пальцем на поле с шариками и перемещай на сенсорных устройствах). Нажми левую кнопку мыши, над полем с шариками (отпусти палец на сенсорных устройствах), чтобы бросить шарик.'
      },
      help_floor: {
        title: 'Движение пола',
        text: 'По ходу выполнения задания, пол будет подниматься по таймеру. При выполнении серии разрушений шариков (комбо) - пол будет опускаться'
      },
      help_rotate_zoom: {
        title: 'Выбери следующий шарик',
        text: 'Нажми на каретку или на кнопку со стрелочками, чтобы поменять местами шарики в каретке (также кнопка ПРОБЕЛ).'
      },
      help_bomb: {
        title: 'Разрушай шарики',
        text: 'Чтобы разрушить шарики на поле, используй кнопку молнии.'
      },
      help_general: {
        title: 'Об игре',
        text: 'В каждом раунде игры, нужно уничтожить шарики из задания. Игра продолжается пока один из шариков не выпадет из корзины.'
      }
    }
  },
  en: {
    code: 'en',
    codeName: 'En',
    name: 'English',
    name_game: 'Battle of tanks',
    workShopTitle: 'Workshop',
    options: {
      health: 'Максимальное HP',
      speed: 'Максимальная скорость',
      speedRotate: 'Максимальная маневренность'
    },

    level: 'Level',
    level_completed: 'Level completed',
    pause: 'Pause',
    create_bomb_help:
      "You don't have any lightning bolts available! Want to create a lightning bolt for viewing an ad?",
    ok: 'Yes',
    cancel: 'No',
    gameover_title: 'The game is lost',
    gameover_btn_continue_by_adv: 'Continue to view ads',
    gameover_btn_new_game: 'Start a new game',
    current_score: 'Current score',
    btnToBattle: 'To battle',
    btn_continue: 'Continue game',
    leaderboard_title: 'Leaders in the game',
    lang_title: 'Language in the game',
    close: 'Close',
    add_bomb_max: 'For destroying the largest balls, you get a bonus - fire lightning!',
    add_bomb_seria: 'For a large series of destruction of balls, you get a bonus - fire lightning!',
    next: 'Далее',
    bonusText: [
      '',
      '',
      'Great',
      'Wonderful',
      'Well done',
      'Brilliantly',
      'Keep it up',
      'Good job',
      'Artfully',
      'Bravo',
      'Fantastic',
      'Very cool',
      'Right On',
      'You are a star'
    ],
    job: 'Objective: Destroy the following balls',
    help: {
      help_move: {
        title: 'Aim and throw the ball',
        text: 'Move the carriage - move the mouse over the field of balls (press your finger on the field of balls and move on mobile devices). Click the mouse button over the field of balls (release your finger on mobile devices) to throw the ball.'
      },
      help_floor: {
        title: 'Floor Movement',
        text: 'When completing the task, the floor will rise according to the timer. When performing a series of broken balls (combos), the floor will go down'
      },
      help_rotate_zoom: {
        title: 'Change next ball',
        text: 'Press the carriage or the arrow button to swap the positions of the balls in the carriage (also the SPACEBAR button).'
      },
      help_bomb: {
        title: 'Wreck the Balls',
        text: 'To destroy the balls on the field, use the close button.'
      },
      help_general: {
        title: 'About the game',
        text: 'In each round of the game it is necessary to remove balls from the task. The game continues until no ball falls out of the basket.'
      }
    }
  }
  // tr: {
  //   code: 'tr',
  //   name: 'Türkçe',
  //   name_game: '2048 balls Deluxe',
  //   record: 'Rekorunuz',
  //   level: 'Seviye',
  //   level_completed: 'Seviye tamamlandı',
  //   pause: 'Duraklat',
  //   create_bomb_help:
  //     'Kullanılabilir yıldırım işaretiniz yok! Bir reklamı görüntülemek için bir şimşek mi oluşturmak istiyorsunuz?',
  //   ok: 'Evet',
  //   cancel: 'Hayir',
  //   gameover_title: 'Oyun kaybedildi',
  //   gameover_btn_continue_by_adv: 'Reklamları görüntülemeye devam et',
  //   gameover_btn_new_game: 'Yeni bir oyun başlat',
  //   current_score: 'Mevcut hesap',
  //   btn_startgame: 'Oyunu başlat',
  //   btn_continue: 'Oyuna Devam Et',
  //   leaderboard_title: 'Oyundaki liderler',
  //   lang_title: 'Oyundaki dil',
  //   close: 'Kapalı',
  //   add_bomb_max: 'En büyük topları yok ettiğinizde bir bonus kazanırsınız - ateş yıldırımı!',
  //   add_bomb_seria: 'Çok sayıda topun yok edilmesi için bir bonus kazanırsınız - ateşli yıldırım!',
  //   next: 'Daha öte',
  //   bonusText: [
  //     '',
  //     '',
  //     'Harika',
  //     'Muhteşem',
  //     'Harika',
  //     'Güzel yapmıştın',
  //     'Parlak',
  //     'İyi uğraştın',
  //     'Aferin',
  //     'İyi iş',
  //     'Fantastik',
  //     'Çok iyi',
  //     'Bu övgüye layık',
  //     'Her zamankinden iyi'
  //   ],
  //   job: 'Amaç: Aşağıdaki topları yok edin'
  // },
  // es: {
  //   code: 'es',
  //   name: 'Español',
  //   name_game: '2048 balls Deluxe',
  //   record: 'Tu récord',
  //   level: 'Nivel',
  //   level_completed: 'Nivel completado',
  //   pause: 'Pausa',
  //   create_bomb_help:
  //     '¡No tienes ningún rayo disponible! ¿Quiere crear un rayo para ver un anuncio?',
  //   ok: 'Sí',
  //   cancel: 'No',
  //   gameover_title: 'el juego esta perdido',
  //   gameover_btn_continue_by_adv: 'Continuar viendo anuncios',
  //   gameover_btn_new_game: 'Empezar un nuevo juego',
  //   current_score: 'Cuenta actual',
  //   btn_startgame: 'Comenzar el juego',
  //   btn_continue: 'Continua el juego',
  //   leaderboard_title: 'Líderes en el juego',
  //   lang_title: 'Idioma en el juego',
  //   close: 'Cerca',
  //   add_bomb_max:
  //     'Por destruir las bolas más grandes, obtienes una bonificación: ¡dispara un rayo!',
  //   add_bomb_seria:
  //     'Por una gran serie de destrucción de bolas, obtienes una bonificación: ¡un rayo de fuego!',
  //   next: 'Más',
  //   bonusText: [
  //     '',
  //     '',
  //     'Excelente',
  //     'Maravilloso',
  //     '¡Bien hecho',
  //     '¡Buen trabajo',
  //     '¡Sigue así',
  //     'Fresco',
  //     'Estupendo',
  //     'БраBravoво',
  //     'Fantástico',
  //     '¡Eres una máquina',
  //     '¡Eres un crack',
  //     'Eres una estrella'
  //   ],
  //   job: 'Objetivo: Destruir las siguientes bolas.'
  // },
  // zh: {
  //   code: 'zh',
  //   name: '中文',
  //   name_game: '2048 balls Deluxe',
  //   record: '你的記錄',
  //   level: '等級',
  //   level_completed: '關卡已完成',
  //   pause: '暫停',
  //   create_bomb_help: '你沒有可用的閃電！ 想要創建閃電來觀看廣告嗎？',
  //   ok: '是的',
  //   cancel: '不',
  //   gameover_title: '比賽輸了',
  //   gameover_btn_continue_by_adv: '繼續查看廣告',
  //   gameover_btn_new_game: '開始新遊戲',
  //   current_score: '往來帳戶',
  //   btn_startgame: '開始遊戲',
  //   btn_continue: '繼續遊戲',
  //   leaderboard_title: '遊戲中的領導者',
  //   lang_title: '遊戲中的語言',
  //   close: '關閉',
  //   add_bomb_max: '摧毀最大的球，您將獲得獎勵 - 火焰閃電！',
  //   add_bomb_seria: '對於大量的破壞球，您將獲得獎勵 - 熾熱的閃電！',
  //   next: '更遠',
  //   bonusText: [
  //     '',
  //     '',
  //     '偉大的',
  //     '精彩的',
  //     '偉大的',
  //     '輝煌地',
  //     '繼續努力吧',
  //     '涼爽的',
  //     '巧妙地',
  //     '布拉沃',
  //     '極佳的',
  //     '精彩的',
  //     '你是一個人才',
  //     '你是個明星'
  //   ],
  //   job: '目標： 摧毀下列球'
  // },
  // ja: {
  //   code: 'ja',
  //   name: '日本語',
  //   name_game: '2048 balls Deluxe',
  //   record: 'あなたの記録',
  //   level: 'レベル',
  //   level_completed: 'レベル完了',
  //   pause: '一時停止',
  //   create_bomb_help: '利用可能な稲妻がありません! 広告を表示するための稲妻を作成したいですか?',
  //   ok: 'はい',
  //   cancel: 'いいえ',
  //   gameover_title: '試合は負けました',
  //   gameover_btn_continue_by_adv: '引き続き広告を表示する',
  //   gameover_btn_new_game: '新しいゲームを始める',
  //   current_score: '当座預金',
  //   btn_startgame: 'ゲームを始める',
  //   btn_continue: 'ゲームを続ける',
  //   leaderboard_title: 'ゲームのリーダー',
  //   lang_title: 'ゲーム内の言語',
  //   close: '近い',
  //   add_bomb_max: '最大のボールを破壊すると、ボーナスとして火の稲妻が得られます。',
  //   add_bomb_seria: 'ボールを大量に破壊すると、ボーナスとして燃えるような稲妻が得られます。',
  //   next: 'さらに遠く',
  //   bonusText: [
  //     '',
  //     '',
  //     '素晴らしい',
  //     '素晴らしい',
  //     '素晴らしい',
  //     '華麗に',
  //     'それを維持する',
  //     'いいね',
  //     '巧みに',
  //     'ブラボー',
  //     '素晴らしい',
  //     '素晴らしい',
  //     'あなたは才能があります',
  //     '君はスター'
  //   ],
  //   job: '目標: 次のボ ー ルを破壊する'
  // },
  // de: {
  //   code: 'de',
  //   name: 'Deutsch',
  //   name_game: '2048 balls Deluxe',
  //   record: 'Ihre Akte',
  //   level: 'Ebene',
  //   level_completed: 'Level abgeschlossen',
  //   pause: 'Pause',
  //   create_bomb_help:
  //     'Sie haben keine Blitze zur Verfügung! Möchten Sie einen Blitz zum Anzeigen einer Anzeige erstellen?',
  //   ok: 'Ja',
  //   cancel: 'Nein',
  //   gameover_title: 'Das Spiel ist verloren',
  //   gameover_btn_continue_by_adv: 'Sehen Sie sich weiterhin Anzeigen an',
  //   gameover_btn_new_game: 'Starten Sie ein neues Spiel',
  //   current_score: 'Aktuelles Konto',
  //   btn_startgame: 'Starte das Spiel',
  //   btn_continue: 'Weiterspielen',
  //   leaderboard_title: 'Anführer im Spiel',
  //   lang_title: 'Sprache im Spiel',
  //   close: 'Schließen',
  //   add_bomb_max: 'Für die Zerstörung der größten Kugeln erhalten Sie einen Bonus – Feuerblitze!',
  //   add_bomb_seria:
  //     'Für eine große Serie der Zerstörung von Bällen erhalten Sie einen Bonus – feurige Blitze!',
  //   next: 'Weiter',
  //   bonusText: [
  //     '',
  //     '',
  //     'Großartig',
  //     'Wunderbar',
  //     'Fein',
  //     'Prima',
  //     'Toll',
  //     'Klasse',
  //     'Sehr schön',
  //     'Gut',
  //     'Fantastisch',
  //     'Ausgezeichnet',
  //     'Du bist ein Talent',
  //     'Du bist ein Star'
  //   ],
  //   job: 'Ziel: Zerstöre die folgenden Bälle',
  //   help: {
  //     help_move: {
  //       title: 'Zielen und den Ball werfen',
  //       text: 'Bewegen Sie die Kutsche – bewegen Sie die Maus über das Ballfeld (drücken Sie Ihren Finger auf das Ballfeld und bewegen Sie sich auf mobilen Geräten). Klicken Sie mit der Maustaste über das Ballfeld (lassen Sie Ihren Finger auf Mobilgeräten los), um den Ball zu werfen.'
  //     },
  //     help_floor: {
  //       title: 'Bodenbewegung',
  //       text: 'Bei Abschluss der Aufgabe wird der Boden entsprechend dem Timer angehoben.“ Bei der Ausführung einer Reihe gebrochener Bälle (Combos) sinkt der Boden'
  //     },
  //     help_rotate_zoom: {
  //       title: 'Nächsten Ball ändern',
  //       text: 'Drücken Sie den Schlitten oder die Pfeiltaste, um die Positionen der Kugeln im Schlitten zu vertauschen (auch die LEERTASTE-Taste).'
  //     },
  //     help_bomb: {
  //       title: 'Wreck the Balls',
  //       text: 'Um die Bälle auf dem Spielfeld zu zerstören, verwenden Sie die Schließen-Taste.'
  //     },
  //     help_general: {
  //       title: 'Über das Spiel',
  //       text: 'In jeder Spielrunde gilt es, Kugeln aus der Aufgabe zu entfernen. Das Spiel wird so lange fortgesetzt, bis kein Ball mehr aus dem Korb fällt.'
  //     }
  //   }
  // }
}
